### ISSUE TITLE
pgvm version display and active indicator  

### ISSUE THREAD

**Issue by tarikkavaz** [vigo/dotfiles-light#3]
just like python and ruby versions  and the [PG] indicator if active

**Comment by vigo** [comment]
PG you mean PostgreSQL ? Already exists

```
[◆ 2.7.0][¶ 3.8.0]
$ postgres_start 
waiting for server to start.... done
server started
----------------------------------------------------------------------------------------------------
[7.77G]
~
[PG][◆ 2.7.0][¶ 3.8.0]
$ 
```

supported indicators `ps1/database-status`

- mysql
- postgresql
- redis
- mongodb

**Comment by ekinertac** [comment]
@tarikkavaz poor guy doesn't know what `pgvm` is. aligopter out.

**Comment by vigo** [comment]
@ekinertac use docker instead of pgvm
